version: '3'
services:
  web:
    build: webserver/.
    container_name: wb-c6-docker
    ports:
      - 80:80
    networks:
      - overlay
    depends_on:
      - db
  db:
    build: database/.
    restart: always
    container_name: db-c6-docker
    volumes:
      - mysqldbv:/var/lib/mysql
    networks: 
      - overlay
      
  adminer:
    image: adminer
    restart: always
    container_name: ad-c6-docker
    ports:
      - 8080:8080
    networks:
      - overlay
    depends_on:
      - db
      - web

volumes:
  mysqldbv:

networks:
  overlay: