version: '3'
services:
  web:
    build: webserver/.
    ports:
      - 80:80
    networks:
      - overlay
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    container_name: db-tsbr-docker
    volumes:
      - mysqldbv:/var/lib/mysql
    networks: 
      - overlay
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "tsbrdocker"
      MYSQL_PASSWORD: "docker"

volumes:
  mysqldbv:

networks:
  overlay: