version: '3'
services:
  web:
    build: webserver/.
    ports:
      - 80:80
    networks:
      - overlay
    depends_on:
      - db
  db:
    build: database/.
    restart: always
    container_name: db-tsbr-docker
    volumes:
      - mysqldbv:/var/lib/mysql
    networks: 
      - overlay

volumes:
  mysqldbv:

networks:
  overlay: